name: seek-sgonzalestest-local-dev-environment
services:
  mysql:
    image: mysql:9.0.1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'seek'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: